### ISSUE TITLE
Setup application-server client error: dial application-server api error: context deadline exceeded

### ISSUE THREAD

**Issue by kannansks** [brocaar/chirpstack-fuota-server#1]
@brocaar 
We installed the FUOTA server using docker compose and when we tried to start it the following error is occurring.

[root@localhost chirpstack-fuota-server]# chirpstack-fuota-server
INFO[0000] starting ChirpStack FUOTA Server              version=SNAPSHOT-fa9c0b9
INFO[0000] storage: connecting to PostgreSQL database
INFO[0000] storage: applying PostgreSQL schema migrations
INFO[0000] client/as: setup application-server client
FATA[0001] setup application-server client error: dial application-server api error: context deadline exceeded

what could be the reason?? the toml file is as follows

chirpstack-fuota-server.toml:
[general]
  # Log level
  #
  # debug=5, info=4, warning=3, error=2, fatal=1, panic=0
  log_level=4

  # Log to syslog.
  #
  # When set to true, log messages are being written to syslog.
  log_to_syslog=false

  # gRPC default resolver scheme.
  #
  # Set this to "dns" for enabling dns round-robin load balancing.
  grpc_default_resolver_scheme=""

# PostgreSQL settings.
#
# Please note that PostgreSQL 9.5+ is required with the 'hstore' extension
# enabled.
[postgresql]
  dsn="postgres://chirpstack_fuota:dbpassword@localhost/chirpstack_fuota?sslmode=disable"

automigrate=true
 max_open_connections=0

  # Max idle connections.
  #
  # This sets the max. number of idle connections in the PostgreSQL connection
  # pool (0 = no idle connections are retained).
  max_idle_connections=2
[application_server]

  # Event handler integration settings.
  [application_server.event_handler]

    # Payload marshaler.
    #
    # This defines how the HTTP payloads are encoded. Valid options are:
    # * protobuf:  Protobuf encoding
    # * json:      JSON encoding (easier for debugging, but less compact than 'protobuf')
    marshaler="protobuf"

    # HTTP handler settings.
    [application_server.event_handler.http]

      # IP:Port to bind the event handler server to.
      bind="0.0.0.0:8090"

  # API integration settings.
  [application_server.api]

    # ChirpStack Application Server API server endpoint.
    server="0.0.0.0:8080"
    # API token.
    token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5X2lkIjoiMjQ0NzRhNzgtMmY1Ni00OWE5LTgyNTktMGNhNmZlZjkyNzJmIiwiYXVkIjoiYXMiLCJpc3MiOiJhcyIsIm5iZiI6MTYxNDkzNTc$

    # Endpoint uses TLS.
    tls_enabled=false

# FUOTA server settings.
[fuota_server]

  # FUOTA server API settings.
  [fuota_server.api]

    # IP:Port to bind the FUOTA server API to.
    bind="0.0.0.0:8070"

    # Optional TLS configuration.
    ca_cert=""
    tls_cert=""
    tls_key=""

**Comment by brocaar** [comment]
```
# ChirpStack Application Server API server endpoint.
server="0.0.0.0:8080"
```

`0.0.0.0` is not a valid IP or hostname you can connect to, hence the error.

**Comment by symovs** [comment]
We have corrected the toml file.

![image](https://user-images.githubusercontent.com/66220236/110108482-40e0a380-7dd2-11eb-9725-029effdf2645.png)

That was a typo as we were cycling between actual IP address, localhost etc as we were getting errors with IP address mentioned.  Sorry about that. Now we are getting the following error 

![image](https://user-images.githubusercontent.com/66220236/110108613-6a013400-7dd2-11eb-991d-73f69b76414d.png)

Our application server is secured using TLS https://10.10.20.61:8080. So do we need to configure the TLS part in the toml ? But in here https://github.com/brocaar/chirpstack-certificates we dont have the certificates for the fuota server. Please help.
