### ISSUE TITLE
Install and get running

### ISSUE THREAD

**Issue by Ich-Bin-eS** [brocaar/chirpstack-fuota-server#4]
HI, i have never used docker before and i am not sure how to get the server running.

I've done 'docker-compose run --rm chirpstack-fuota-server bash'
and all steps of 'make' successfully.

After that im not able to set the database up while im using the containers bash.
Furthermore i can not find the executable application mentioned here:

Usage:
  chirpstack-fuota-server [flags]
  chirpstack-fuota-server [command]

So which steps are missing after making the server?

**Comment by Ich-Bin-eS** [comment]
solved

**Comment by shabaz-git** [comment]
Hi @Ich-Bin-eS ,

> After that im not able to set the database up while im using the containers bash.
> Furthermore i can not find the executable application mentioned here:
How did you solve this issue? 
In my case remain all from Gateway-bridge to APP-Server and Database are lying outside the docker. 
And if you too installed the database outside the docker container, how you are able to communicate fuota-DB and fuota-server?
Can you please suggest the steps to follow?

**Comment by Ich-Bin-eS** [comment]
Hi,

sorry it's been a while and im not sure what i've done exactly. 

I think the problem in my case was just the wrong config file for starting the fuota server. 
To get it running i used "chirpstack-fuota-server --config build/chirpstack-fuota-server.toml"

And you have to enter the db user credentials of course
